@startuml

!include <cloudinsight/rabbitmq>
!include <cloudinsight/docker>
!include <cloudinsight/mysql>
'//  !include <cloudinsight/redis>

'//     artifact "<$redis>\nredis" as redis
database "<$mysql>\ntasklogs" as DB
artifact "<$rabbitmq>" as MOM {
    queue "bulletin-board" as queue1
    queue "tasks-pool" as queue2
}

frame services {
    artifact BottlesShop <<Service>>
    artifact PlasticWarehouse <<Service>>
    collections BottlesFactory <<Service>>
    note left: self-healing
}

frame greta-services {
    collections GretaSpy <<Service>>
    artifact GretaCommitteeCoordinator <<Service>>
}

frame tasks {
    artifact GretaCommittee <<Task>>
}

interface HTTP as http1
interface HTTP as http2

http1 -[#green,bold]-> BottlesShop
http2 -[#red,bold]-> PlasticWarehouse
GretaCommittee -up-> DB
BottlesFactory ..> queue1
PlasticWarehouse -[#red,bold]-> BottlesFactory
queue1 .> BottlesShop
queue1 ..> GretaSpy
GretaSpy ..> queue2
queue2 ..> GretaCommitteeCoordinator
GretaCommitteeCoordinator -> GretaCommittee

@enduml